# Generated by Django 4.0.1 on 2022-02-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('discription', models.CharField(max_length=100)),
                ('spefication', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
